package files;

public class payload {
	
	public static String AddPlace()
	{
		return "{\r\n"
				+ "    \"flowName\": \"API_tc03\",\r\n"
				+ "    \"developers\": \"keval.k\",\r\n"
				+ "    \"reviewers\": \"adit.s,ankit.mis,ankur.y,balakarthikeyan.r,hande.s,hemali.d,nitish.sha,surya.s,umang.s\",\r\n"
				+ "    \"mode\": \"EDIT\",\r\n"
				+ "    \"datastoreList\": [\r\n"
				+ "        {\r\n"
				+ "            \"type\": \"DruidDataStore\",\r\n"
				+ "            \"connectionId\": 10,\r\n"
				+ "            \"uId\": 998,\r\n"
				+ "            \"config\": {\r\n"
				+ "                \"Server\": \"http://c8-auto-druid-staging-2.srv.media.net:8090\",\r\n"
				+ "                \"Indexer\": \"http://172.16.200.30:10141\",\r\n"
				+ "                \"Broker\": \"http://c8-auto-druid-staging-2.srv.media.net:8082\",\r\n"
				+ "                \"dataSource\": \"API_tc03\",\r\n"
				+ "                \"dm_source\": \"None\",\r\n"
				+ "                \"enable_compaction\": \"false\"\r\n"
				+ "            },\r\n"
				+ "            \"forceUpdate\": false,\r\n"
				+ "            \"id\": 998\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"type\": \"KafkaDataStore\",\r\n"
				+ "            \"connectionId\": 3,\r\n"
				+ "            \"uId\": 997,\r\n"
				+ "            \"config\": {\r\n"
				+ "                \"bootStrapServer\": \"172.16.201.187:9092,172.16.201.188:9092,172.16.201.189:9092\",\r\n"
				+ "                \"topics\": \"API_tc03\",\r\n"
				+ "                \"use_regex\": \"0\",\r\n"
				+ "                \"is_active\": \"0\",\r\n"
				+ "                \"source\": \"\",\r\n"
				+ "                \"maxOffsetsPerTrigger\": \"1000000\",\r\n"
				+ "                \"output_column_format\": \"yyyyMMddHH\",\r\n"
				+ "                \"pool_id\": \"2\",\r\n"
				+ "                \"parser_class\": \"net.media.spark.util.JsonDataFrameParser\",\r\n"
				+ "                \"startingOffsets\": \"latest\",\r\n"
				+ "                \"input_column_key\": \"\",\r\n"
				+ "                \"input_column_format\": \"yyyy-MM-dd HH:mm:ss\",\r\n"
				+ "                \"raven_schema_id\": \"none\"\r\n"
				+ "            },\r\n"
				+ "            \"forceUpdate\": false,\r\n"
				+ "            \"id\": 997\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		
	}
	
	public static String SaveFlow()
	{
		return"{\r\n"
				+ "  \"flow\": \"API_tc03\",\r\n"
				+ "  \"edges\": [\r\n"
				+ "    {\r\n"
				+ "      \"source\": 997,\r\n"
				+ "      \"sink\": 998,\r\n"
				+ "      \"type\": \"DruidStreamEdge\",\r\n"
				+ "      \"group\": 1,\r\n"
				+ "      \"config\": {\r\n"
				+ "        \"context\": \"{}\",\r\n"
				+ "        \"replicas\": \"1\",\r\n"
				+ "        \"task_count\": \"1\",\r\n"
				+ "        \"completion_timeout\": \"PT1800S\",\r\n"
				+ "        \"late_message_rejection_period\": \"PT3600S\",\r\n"
				+ "        \"early_message_rejection_period\": \"PT3600S\",\r\n"
				+ "        \"aggregated_lag_offsets\": \"100000\",\r\n"
				+ "        \"delay_of_druid_real_time\": \"60\",\r\n"
				+ "        \"process_failed\": \"10\",\r\n"
				+ "        \"auto_restart_on_kill\": \"true\",\r\n"
				+ "        \"auto_reset_on_delay\": \"true\",\r\n"
				+ "        \"max_rows_per_segment\": \"1000000\",\r\n"
				+ "        \"segment_granularity\": \"HOUR\",\r\n"
				+ "        \"query_granularity\": \"MINUTE\",\r\n"
				+ "        \"schema_source_key\": \"None\",\r\n"
				+ "        \"parser_spec_format_type\": \"json\",\r\n"
				+ "        \"schema_source\": \"fields_meta\",\r\n"
				+ "        \"max_rows_in_memory\": \"500000\",\r\n"
				+ "        \"column\": \"time_stamp\",\r\n"
				+ "        \"transform_spec\": \"{}\",\r\n"
				+ "        \"enable_consistency_alerts\": \"true\",\r\n"
				+ "        \"row_count_deviation_percentage\": \"0:0\"\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"groups\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": 1,\r\n"
				+ "      \"title\": \"Group 1\",\r\n"
				+ "      \"description\": \"\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"team_id\": 314,\r\n"
				+ "  \"flow_use_case\": \"7\",\r\n"
				+ "   \"flock_active\": 0 ,\r\n"
				+ "   \"soc_active\": 0 ,\r\n"
				+ "   \"mode\": \"EDIT\"\r\n"
				+ "}";
	}
	

	

}
